
database:

  # the name of your JDBC driver
  driverClass: org.h2.Driver

  # the username
  user: Granit

  # the password
  password: 28Qershor2002

  # the JDBC URL
  url: jdbc:h2:tcp://localhost/C:/Users/Admin/Desktop/work-log

server:
  type;: simple
  connector:
    type: http
    port: 8083